all:
  children:
    webservers:
      hosts:
        web01:
          ansible_host: 10.0.1.10
        web02:
          ansible_host: 10.0.1.11
    
    databases:
      hosts:
        db01:
          ansible_host: 10.0.2.10
    
    kubernetes:
      children:
        k8s_masters:
          hosts:
            master01:
              ansible_host: 10.0.3.10
        k8s_workers:
          hosts:
            worker01:
              ansible_host: 10.0.3.20
            worker02:
              ansible_host: 10.0.3.21

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3

